paginate: 1
paginate_path: /blog/page/:num/
permalink: /posts/:categories/:year/:month/:day/:title/index:output_ext
defaults:
  - values:
      layout: bootstrap_5.2.3
  - scope:
      type: "posts"
    values:
      layoyt: post
