paginate: 1
paginate_path: /posts/page/:num/
permalink: /posts/:categories/:year/:month/:day/:title/index:output_ext
defaults:
  - values:
      layout: bootstrap_5.2.3
  - scope:
      type: posts
    values:
      layout: post
